### PR TITLE
add image fit

### PR DESCRIPTION
**Pull request by akindone**

### CODE REVIEW

**Comment by akindone** [comment]
@aliyigitbireroglu Can you review this PR?

**Comment by aliyigitbireroglu** [comment]
The image fit is a good addition, I appreciate, but I don't really like this formatting. I think it makes it more difficult to read the code for future development.

**Comment by akindone** [comment]
> The image fit is a good addition, I appreciate, but I don't really like this formatting. I think it makes it more difficult to read the code for future development.

have revert the format modify

**Comment by akindone** [comment]
@aliyigitbireroglu Can you review this PR, please

**Comment by aliyigitbireroglu** [comment]
Thank you for the PR, looks great. I will update on pubdev as well.

**Pull request merged**
